version: "3.8"
services:
  backend:
    image: "denihax/gpustalker:2.5.2022.21.13.16"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}