name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  POSTGRESQL_VERSION: 13.4
  POSTGRESQL_DB: emaildb
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  JAVA_VERSION: 1.17
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run:
          mvn --no-transfer-progress -DBESTBUY_API_KEY=${{ secrets.BESTBUY_API_KEY }} -D EMAIL_PASSWORD=${{ env.EMAIL_PASSWORD }} -D DB_URL=${{ env.DB_URL }} -D DB_USERNAME=${{ env.DB_USERNAME }} -D DB_PASSWORD=${{ env.DB_PASSWORD }} clean package -P build-frontend